<head>
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<!--site by Stephen Breighner special thanks @abraham  at github!-->



<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>

<meta name="viewport" content="width=device-width, initial-scale=1">
<title>My Twittr Memories</title>
<link type ="text/css" href="tm_style.css" media="all" rel="stylesheet"/>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <body>
    <div>
<h2>My Twittr Memories...</h2><h6 >a place to go for people thinking of leaving the twitter world

</h6>
        
      <hr />
   
    </div>
  
    <p>
  
        <?php echo($content);
        ?>
     
    </p>

  </body>
</html>
